HEADLESS: true
STATIC_WAIT: 3
RETRY_ATTEMPTS: 3
BROWSER: chromium
DYNAMIC_WAIT: 30000
VIEWPORT_WIDTH: 1920
VIEWPORT_HEIGHT: 1080
REPORT_PATH: features/reports
EXPORTS_PATH: features/exports
LOG_PATH: features/logs/app.log
PROJECT: Practice Test Automation
VIDEO_PATH: features/reports/video
TEST_DATA_PATH: features/test_data
TRACE_PATH: features/reports/trace.zip
BASE_URL: https://practicetestautomation.com
SCREENSHOT_PATH: features/reports/screenshots
ALLURE_REPORT_PATH: features/reports/allure-report
HTML_REPORT_PATH: features/reports/html-report.html
ALLURE_RESULTS_PATH: features/reports/allure-results
NETWORK_CALLS_PATH: features/logs/network_calls.html

